#!/bin/sh

CURL=`which curl 2>/dev/null`
WGET=`which wget 2>/dev/null`
OUI_DOWNLOAD_URL="http://standards.ieee.org/develop/regauth/oui/oui.txt"

OUI_PATH0="/etc/aircrack-ng"
OUI_PATH1="/usr/local/etc/aircrack-ng"
OUI_PATH2="/usr/share/aircrack-ng"
for OUI in \
    "/etc/aircrack-ng/airodump-ng-oui.txt" \
    "/usr/local/etc/aircrack-ng/airodump-ng-oui.txt" \
    "/usr/share/aircrack-ng/airodump-ng-oui.txt" \
    "/var/lib/misc/oui.txt" \
    "/usr/share/misc/oui.txt" \
    "/var/lib/ieee-data/oui.txt" \
    "/usr/share/ieee-data/oui.txt" \
    "/etc/manuf/oui.txt" \
    "/usr/share/wireshark/wireshark/manuf/oui.txt" \
    "/usr/share/wireshark/manuf/oui.txt" \
    "NULL"
do
	if [ -d "$(dirname "$OUI")" ]; then
		break
	fi
done

if [ "$OUI" = "NULL" ]; then
	OUI="${OUI_PATH0}/airodump-ng-oui.txt"
fi
OUI_PATH="$(dirname "$OUI")"
AIRODUMP_NG_OUI="${OUI_PATH}/airodump-ng-oui.txt"
OUI_IEEE="${OUI_PATH}/oui.txt"
USERID=""


# Make sure the user is root
if [ x"`which id 2> /dev/null`" != "x" ]
then
	USERID="`id -u 2> /dev/null`"
fi

if [ x$USERID = "x" -a x$UID != "x" ]
then
	USERID=$UID
fi

if [ x$USERID != "x" -a x$USERID != "x0" ]
then
	echo Run it as root ; exit ;
fi


mkdir -p ${OUI_PATH}

if [ ${CURL} ] || [ ${WGET} ]; then
	# Delete previous partially downloaded file (if the script was aborted)
	rm -f ${OUI_IEEE} >/dev/null 2>/dev/null

	# Download it
	echo "[*] Downloading IEEE OUI file..."

	if [ ${WGET} ]; then
		${WGET} ${OUI_DOWNLOAD_URL} -O ${OUI_IEEE} >/dev/null 2>/dev/null
	else
		${CURL} -L ${OUI_DOWNLOAD_URL} > ${OUI_IEEE} 2>/dev/null
	fi

	if [ "${?}" -ne 0 ]; then
		echo "[*] Error: Failed to download OUI list, aborting..."
		exit 1
	fi

	# Parse the downloaded OUI list
	echo "[*] Parsing OUI file..."

	# Keep the previous file
	if [ -f "${AIRODUMP_NG_OUI}" ]; then
		mv ${AIRODUMP_NG_OUI} ${AIRODUMP_NG_OUI}-old
	fi

	# Parse it
	grep "(hex)" ${OUI_IEEE} | sed 's/^[ \t]*//g;s/[ \t]*$//g' > ${AIRODUMP_NG_OUI}
	if [ ! -s "${AIRODUMP_NG_OUI}" ]; then
		if [ -f "${AIRODUMP_NG_OUI}-old" ]; then
			mv ${AIRODUMP_NG_OUI}-old ${AIRODUMP_NG_OUI}
		fi
		echo "[*] Error: Failed to parse OUI, aborting..."
		exit 1
	fi

	case "${OUI_PATH}" in
	"${OUI_PATH0}" | "${OUI_PATH1}" | "${OUI_PATH2}") ;;
	*)
		if [ ! -d "${OUI_PATH0}" ]; then
			ln -s ${OUI_PATH} ${OUI_PATH0}
		fi ;;
	esac

	# Cleanup
	rm -f ${AIRODUMP_NG_OUI}-old

	echo "[*] Airodump-ng OUI file successfully updated"
else
	if [ -f "${OUI}" ]; then
		echo "[*] Please install curl or wget to update OUI list"
	else
		echo "[*] Please install curl or wget to install OUI list"
	fi
	exit 1
fi

exit 0
